// <auto-generated>
//   This file mirrors what Visual Studio's ResXFileCodeGenerator custom
//   tool would normally produce from Strings.resx, but it's hand-written
//   because `dotnet build`/`dotnet publish` on this repo's Linux
//   toolchain never runs that VS-only design-time step — see CLAUDE.md
//   for the other Linux-cross-compile workarounds this project needs.
//
//   If you add a new key to Strings.resx (and its Strings.zh-TW.resx
//   satellite), add a matching property here with the same name.
// </auto-generated>

using System.Resources;

namespace FolderLinkApp;

/// <summary>
/// Strongly-typed accessor for the UI strings in Strings.resx (English,
/// the neutral/default resource) and Strings.zh-TW.resx (the Traditional
/// Chinese satellite). Resolution follows whatever culture is set on
/// Thread.CurrentThread.CurrentUICulture — see Program.Main, which sets
/// it once at startup from the OS display-language setting — so no
/// culture needs to be threaded through call sites here.
/// </summary>
internal static class Strings
{
    // The resource's manifest base name. The .NET SDK embeds Strings.resx
    // as "<RootNamespace>.Strings.resources", so this must match the
    // <RootNamespace> in FolderLink.csproj (set to "FolderLinkApp" to
    // match this file's C# namespace). It previously said "FolderLink",
    // which compiled fine but made the first Strings lookup in MainForm's
    // constructor throw MissingManifestResourceException, killing the exe
    // at launch before any window appeared.
    private static readonly ResourceManager ResourceManager =
        new("FolderLinkApp.Strings", typeof(Strings).Assembly);

    internal static string FormTitle => Get(nameof(FormTitle));
    internal static string SourceFolderLabel => Get(nameof(SourceFolderLabel));
    internal static string DestFolderLabel => Get(nameof(DestFolderLabel));
    internal static string BrowseButton => Get(nameof(BrowseButton));
    internal static string StartButton => Get(nameof(StartButton));
    internal static string CancelButton => Get(nameof(CancelButton));
    internal static string SourceBrowseDialogDescription => Get(nameof(SourceBrowseDialogDescription));
    internal static string DestBrowseDialogDescription => Get(nameof(DestBrowseDialogDescription));

    internal static string StatusFormat => Get(nameof(StatusFormat));
    internal static string StatusIdle => Get(nameof(StatusIdle));
    internal static string StatusCopying => Get(nameof(StatusCopying));
    internal static string StatusStartFailed => Get(nameof(StatusStartFailed));
    internal static string StatusFinishingUp => Get(nameof(StatusFinishingUp));
    internal static string StatusCompletedWithErrors => Get(nameof(StatusCompletedWithErrors));
    internal static string StatusCompletedNeedsManualCheck => Get(nameof(StatusCompletedNeedsManualCheck));
    internal static string StatusCompletedLeftoverFiles => Get(nameof(StatusCompletedLeftoverFiles));
    internal static string StatusCompleted => Get(nameof(StatusCompleted));
    internal static string StatusFinalizeFailed => Get(nameof(StatusFinalizeFailed));
    internal static string StatusCancelled => Get(nameof(StatusCancelled));

    internal static string ConfirmMoveTitle => Get(nameof(ConfirmMoveTitle));
    internal static string ConfirmMoveBody => Get(nameof(ConfirmMoveBody));

    internal static string LogTransferStarting => Get(nameof(LogTransferStarting));
    internal static string LogRoboStartFailed => Get(nameof(LogRoboStartFailed));
    internal static string LogRoboError => Get(nameof(LogRoboError));
    internal static string LogRoboErrorLocked => Get(nameof(LogRoboErrorLocked));
    internal static string LogRoboErrorAlreadyMoved => Get(nameof(LogRoboErrorAlreadyMoved));
    internal static string LogRoboErrorRetryHint => Get(nameof(LogRoboErrorRetryHint));
    internal static string ErrorSomeFilesInUseBody => Get(nameof(ErrorSomeFilesInUseBody));

    internal static string LogAllFilesCopied => Get(nameof(LogAllFilesCopied));
    internal static string LogCannotConfirmEmpty => Get(nameof(LogCannotConfirmEmpty));
    internal static string LogLeftoverWarning => Get(nameof(LogLeftoverWarning));
    internal static string LogSymlinkCreated => Get(nameof(LogSymlinkCreated));
    internal static string CompletionBody => Get(nameof(CompletionBody));
    internal static string LogFinalizeError => Get(nameof(LogFinalizeError));
    internal static string FinalizeErrorBody => Get(nameof(FinalizeErrorBody));
    internal static string LogCancelledByUser => Get(nameof(LogCancelledByUser));
    internal static string ClosingConfirmBody => Get(nameof(ClosingConfirmBody));

    private static string Get(string name) => ResourceManager.GetString(name) ?? name;
}
