// <auto-generated>
//   Hand-written to mirror what Visual Studio's ResXFileCodeGenerator
//   custom tool would normally produce from CoreStrings.resx. This
//   project is built with plain `dotnet build`/`dotnet test` on Linux
//   (see CLAUDE.md), which never runs that VS-only design-time step, so
//   there's no automatic generator to rely on here.
//
//   If you add a new key to CoreStrings.resx (and its
//   CoreStrings.zh-TW.resx satellite), add a matching property here with
//   the same name.
// </auto-generated>

using System.Resources;

namespace FolderLinkApp;

/// <summary>
/// Strongly-typed accessor for the pre-flight refusal messages used by
/// TransferSafety. Resolves via CoreStrings.resx (English, the
/// neutral/default resource) and CoreStrings.zh-TW.resx (the Traditional
/// Chinese satellite), following whatever culture is set on
/// Thread.CurrentThread.CurrentUICulture — the FolderLink WinForms
/// project sets this once at startup from the OS display-language
/// setting (see Program.Main), and this class picks it up the same way
/// the UI-layer Strings class does, without needing the culture threaded
/// through TransferSafety's own call sites.
///
/// Named "CoreStrings" (not "Strings") specifically to avoid colliding
/// with FolderLinkApp.Strings in the FolderLink project: both share the
/// FolderLinkApp C# namespace, and FolderLink references FolderLink.Core,
/// so two same-named "Strings" classes would be ambiguous wherever both
/// are in scope.
/// </summary>
internal static class CoreStrings
{
    // The resource's manifest base name. The .NET SDK embeds
    // CoreStrings.resx as "<RootNamespace>.CoreStrings.resources", so
    // this must match the <RootNamespace> in FolderLink.Core.csproj
    // ("FolderLinkApp"). dotnet test fails with
    // MissingManifestResourceException if the two ever drift apart.
    private static readonly ResourceManager ResourceManager =
        new("FolderLinkApp.CoreStrings", typeof(CoreStrings).Assembly);

    internal static string BothPathsRequired => Get(nameof(BothPathsRequired));
    internal static string SourceDoesNotExist => Get(nameof(SourceDoesNotExist));
    internal static string SourceIsAlreadyLink => Get(nameof(SourceIsAlreadyLink));
    internal static string SourceEqualsDestination => Get(nameof(SourceEqualsDestination));
    internal static string DestinationInsideSource => Get(nameof(DestinationInsideSource));
    internal static string SourceInsideDestination => Get(nameof(SourceInsideDestination));
    internal static string DestinationIsAlreadyLink => Get(nameof(DestinationIsAlreadyLink));
    internal static string InsufficientDiskSpace => Get(nameof(InsufficientDiskSpace));

    private static string Get(string name) => ResourceManager.GetString(name) ?? name;
}
